### ISSUE TITLE
Support OAI-PMH data set representing deleted objects

### ISSUE THREAD

**Issue by paluchas** [digital-york/oai-pmh#2]
# What
As a Primo (and other aggregated systems) admin, I would like the OAI-PMH feed to indicate what objects are removed and when. 

# Why
If objects are removed from Digital Libary this information is not presented in a defined way through OAI-PMH feed. Currently, a manual process is required to remove records from Yorsearch (Primo) system. This requires two steps:
* create an OAI-PMH XML file including records to be deleted
* running the deletion pipe with the above file uploaded to Primo filesystem

Wiki documentation about this process - [closed link](https://wiki.york.ac.uk/display/dlib/Manually+deleting+a+record+from+Primo)

# How
We need to investigate how to construct a proper OAI-PMH data set representing all deleted objects. This URL should be used in updated Primo pipe.

**Comment by paluchas** [comment]
Ther is some wiki documentation ([closed link](https://wiki.york.ac.uk/display/dlib/OAI-PMH)) how sets could be defined.

**Comment by Jimadine** [comment]
Closing this in anticipation of archiving this repository.
